spring.application.name=email-writer


# AI Config:
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-3.1-flash-lite-preview
ai.maxTokens=500